// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TriajeApp.DataContext;

namespace TriajeApp.Migrations
{
    [DbContext(typeof(EncuestaDataContext))]
    partial class EncuestaDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TriajeApp.Models.Encuesta", b =>
                {
                    b.Property<int>("encuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("alertaIncapacidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cercaniaCovid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empleadoBarcode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empleadoDNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("empleadoEdad")
                        .HasColumnType("int");

                    b.Property<string>("empleadoIncapacitado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empleadoNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empleadoSexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empleadoSintomas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empleadoTelefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("empleadoTemperatura")
                        .HasColumnType("int");

                    b.Property<string>("empleadoVacunado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empresaEdificio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empresaNivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("empresaNombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("encuestaFecha")
                        .HasColumnType("datetime");

                    b.Property<string>("encuestaTipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("haViajado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kitBienvenida")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reintegroIncapacidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("encuestaId");

                    b.ToTable("Encuesta", "dbo");
                });
#pragma warning restore 612, 618
        }
    }
}
